# Generated by Django 3.1.7 on 2021-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(default='B+', max_length=4),
            preserve_default=False,
        ),
    ]
