# Generated by Django 3.1.7 on 2021-04-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_patient_assigneddoctorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
    ]
