# Generated by Django 3.0.5 on 2021-04-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20210412_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='cost_for_one',
            new_name='costForOne',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='med_id',
            new_name='medId',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='med_name',
            new_name='medName',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='quantity',
            new_name='stock',
        ),
    ]
